spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id:
            client-secret:
          kakao:
            authorization-grant-type: authorization_code
            scope: profile
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            client-name: Kakao
            client-authentication-method: POST
            client-id:
            client-secret:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    mode: HTML5