drop table if exists users;
create table users (
 id bigint generated by default as identity,
 name varchar(100),
-- email varchar(1000),
 provider varchar(30),
 token varchar(1000),
-- content varchar(2000),
-- created_at timestamp,
-- done boolean,
-- modified_at timestamp,
 primary key (id)
);